with-expecter: true
inpackage: true
quiet: False
filename: "{{.InterfaceName | snakecase}}_mock.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
packages:
    github.com/fedeizzo/gonetworth/internal/db:
      config:
        recursive: true
      interfaces:
        Querier:
