// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID    int32
	Name  string
	Notes *string
	Align pgtype.Numeric
}

type Budget struct {
	ID       int32
	Amount   float64
	Category *int32
}

type Expense struct {
	ID          int32
	Amount      float64
	Description *string
	Date        time.Time
	Source      *int32
	Destination *int32
	Category    *int32
}

type ExpenseAccount struct {
	ID    int32
	Name  string
	Notes *string
}

type ExpenseCategory struct {
	ID    int32
	Name  string
	Notes *string
}

type Income struct {
	ID          int32
	Amount      float64
	Description *string
	Date        time.Time
	Source      *int32
	Destination *int32
	Category    *int32
}

type IncomeAccount struct {
	ID    int32
	Name  string
	Notes *string
}

type IncomeCategory struct {
	ID    int32
	Name  string
	Notes *string
}

type Transfer struct {
	ID          int32
	Amount      float64
	Description *string
	Date        time.Time
	Source      *int32
	Destination *int32
	Category    *int32
}

type TransferCategory struct {
	ID    int32
	Name  string
	Notes *string
}
