// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID    int32
	Name  string
	Notes pgtype.Text
	Align pgtype.Numeric
}

type Budget struct {
	ID       int32
	Amount   pgtype.Numeric
	Category pgtype.Int4
}

type Expense struct {
	ID          int32
	Amount      pgtype.Numeric
	Description pgtype.Text
	Date        pgtype.Date
	Source      pgtype.Int4
	Destination pgtype.Int4
	Category    pgtype.Int4
}

type ExpenseAccount struct {
	ID    int32
	Name  string
	Notes pgtype.Text
}

type ExpenseCategory struct {
	ID    int32
	Name  string
	Notes pgtype.Text
}

type Income struct {
	ID          int32
	Amount      pgtype.Numeric
	Description pgtype.Text
	Date        pgtype.Date
	Source      pgtype.Int4
	Destination pgtype.Int4
	Category    pgtype.Int4
}

type IncomeAccount struct {
	ID    int32
	Name  string
	Notes pgtype.Text
}

type IncomeCategory struct {
	ID    int32
	Name  string
	Notes pgtype.Text
}

type Transfer struct {
	ID          int32
	Amount      pgtype.Numeric
	Description pgtype.Text
	Date        pgtype.Date
	Source      pgtype.Int4
	Destination pgtype.Int4
	Category    pgtype.Int4
}

type TransferCategory struct {
	ID    int32
	Name  string
	Notes pgtype.Text
}
